//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 12:16:00 AM CET 
//


package com.sp.ScientificPublications.models.paper_review;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TOption.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TOption"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Strongly disagree"/&gt;
 *     &lt;enumeration value="Disagree"/&gt;
 *     &lt;enumeration value="Neutral"/&gt;
 *     &lt;enumeration value="Agree"/&gt;
 *     &lt;enumeration value="Strongly agree"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TOption")
@XmlEnum
public enum TOption {

    @XmlEnumValue("Strongly disagree")
    STRONGLY_DISAGREE("Strongly disagree"),
    @XmlEnumValue("Disagree")
    DISAGREE("Disagree"),
    @XmlEnumValue("Neutral")
    NEUTRAL("Neutral"),
    @XmlEnumValue("Agree")
    AGREE("Agree"),
    @XmlEnumValue("Strongly agree")
    STRONGLY_AGREE("Strongly agree");
    private final String value;

    TOption(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TOption fromValue(String v) {
        for (TOption c: TOption.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
