//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 12:16:00 AM CET 
//


package com.sp.ScientificPublications.models.paper_review;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRecommendation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRecommendation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Accept"/&gt;
 *     &lt;enumeration value="Reject"/&gt;
 *     &lt;enumeration value="Minor Revisions"/&gt;
 *     &lt;enumeration value="Major Revisions"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TRecommendation")
@XmlEnum
public enum TRecommendation {

    @XmlEnumValue("Accept")
    ACCEPT("Accept"),
    @XmlEnumValue("Reject")
    REJECT("Reject"),
    @XmlEnumValue("Minor Revisions")
    MINOR_REVISIONS("Minor Revisions"),
    @XmlEnumValue("Major Revisions")
    MAJOR_REVISIONS("Major Revisions");
    private final String value;

    TRecommendation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRecommendation fromValue(String v) {
        for (TRecommendation c: TRecommendation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
