//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 12:41:41 PM CET 
//


package com.sp.ScientificPublications.models.document_revision;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recommendation" type="{http://www.ftn.uns.ac.rs/scientific-publication}TRecommendation"/>
 *         &lt;element name="questionare" type="{http://www.ftn.uns.ac.rs/scientific-publication}TQuestionare"/>
 *         &lt;element name="comments-to-author" type="{http://www.ftn.uns.ac.rs/scientific-publication}TComments"/>
 *         &lt;element name="comments-to-editor" type="{http://www.ftn.uns.ac.rs/scientific-publication}TComments"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.ftn.uns.ac.rs/common}TPositiveInteger" />
 *       &lt;attribute name="paper-id" use="required" type="{http://www.ftn.uns.ac.rs/common}TPositiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recommendation",
    "questionare",
    "commentsToAuthor",
    "commentsToEditor"
})
@XmlRootElement(name = "document-revision")
public class DocumentRevision {

    @XmlElement(required = true)
    protected TRecommendation recommendation;
    @XmlElement(required = true)
    protected TQuestionare questionare;
    @XmlElement(name = "comments-to-author", required = true)
    protected TComments commentsToAuthor;
    @XmlElement(name = "comments-to-editor", required = true)
    protected TComments commentsToEditor;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "paper-id", required = true)
    protected BigInteger paperId;

    /**
     * Gets the value of the recommendation property.
     * 
     * @return
     *     possible object is
     *     {@link TRecommendation }
     *     
     */
    public TRecommendation getRecommendation() {
        return recommendation;
    }

    /**
     * Sets the value of the recommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRecommendation }
     *     
     */
    public void setRecommendation(TRecommendation value) {
        this.recommendation = value;
    }

    /**
     * Gets the value of the questionare property.
     * 
     * @return
     *     possible object is
     *     {@link TQuestionare }
     *     
     */
    public TQuestionare getQuestionare() {
        return questionare;
    }

    /**
     * Sets the value of the questionare property.
     * 
     * @param value
     *     allowed object is
     *     {@link TQuestionare }
     *     
     */
    public void setQuestionare(TQuestionare value) {
        this.questionare = value;
    }

    /**
     * Gets the value of the commentsToAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link TComments }
     *     
     */
    public TComments getCommentsToAuthor() {
        return commentsToAuthor;
    }

    /**
     * Sets the value of the commentsToAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TComments }
     *     
     */
    public void setCommentsToAuthor(TComments value) {
        this.commentsToAuthor = value;
    }

    /**
     * Gets the value of the commentsToEditor property.
     * 
     * @return
     *     possible object is
     *     {@link TComments }
     *     
     */
    public TComments getCommentsToEditor() {
        return commentsToEditor;
    }

    /**
     * Sets the value of the commentsToEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TComments }
     *     
     */
    public void setCommentsToEditor(TComments value) {
        this.commentsToEditor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the paperId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaperId() {
        return paperId;
    }

    /**
     * Sets the value of the paperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaperId(BigInteger value) {
        this.paperId = value;
    }

}
