//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 12:41:41 PM CET 
//


package com.sp.ScientificPublications.models.document_revision;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TOption.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TOption">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Strongly disagree"/>
 *     &lt;enumeration value="Disagree"/>
 *     &lt;enumeration value="Neutral"/>
 *     &lt;enumeration value="Agree"/>
 *     &lt;enumeration value="Strongly agree"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TOption")
@XmlEnum
public enum TOption {

    @XmlEnumValue("Strongly disagree")
    STRONGLY_DISAGREE("Strongly disagree"),
    @XmlEnumValue("Disagree")
    DISAGREE("Disagree"),
    @XmlEnumValue("Neutral")
    NEUTRAL("Neutral"),
    @XmlEnumValue("Agree")
    AGREE("Agree"),
    @XmlEnumValue("Strongly agree")
    STRONGLY_AGREE("Strongly agree");
    private final String value;

    TOption(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TOption fromValue(String v) {
        for (TOption c: TOption.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
