//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 12:41:41 PM CET 
//


package com.sp.ScientificPublications.models.document_revision;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRecommendation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRecommendation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Accept"/>
 *     &lt;enumeration value="Reject"/>
 *     &lt;enumeration value="Minor Revisions"/>
 *     &lt;enumeration value="Major Revisions"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRecommendation")
@XmlEnum
public enum TRecommendation {

    @XmlEnumValue("Accept")
    ACCEPT("Accept"),
    @XmlEnumValue("Reject")
    REJECT("Reject"),
    @XmlEnumValue("Minor Revisions")
    MINOR_REVISIONS("Minor Revisions"),
    @XmlEnumValue("Major Revisions")
    MAJOR_REVISIONS("Major Revisions");
    private final String value;

    TRecommendation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRecommendation fromValue(String v) {
        for (TRecommendation c: TRecommendation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
