//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 12:10:40 AM CET 
//


package com.sp.ScientificPublications.models.cover_letter;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sender-contact" type="{http://www.ftn.uns.ac.rs/scientific-publication}TContact"/&gt;
 *         &lt;element name="employer-contact" type="{http://www.ftn.uns.ac.rs/scientific-publication}TContact"/&gt;
 *         &lt;element name="body" type="{http://www.ftn.uns.ac.rs/scientific-publication}TBody"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderContact",
    "employerContact",
    "body"
})
@XmlRootElement(name = "cover-letter")
public class CoverLetter {

    @XmlElement(name = "sender-contact", required = true)
    protected TContact senderContact;
    @XmlElement(name = "employer-contact", required = true)
    protected TContact employerContact;
    @XmlElement(required = true)
    protected TBody body;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the senderContact property.
     *
     * @return
     *     possible object is
     *     {@link TContact }
     *
     */
    public TContact getSenderContact() {
        return senderContact;
    }

    /**
     * Sets the value of the senderContact property.
     *
     * @param value
     *     allowed object is
     *     {@link TContact }
     *
     */
    public void setSenderContact(TContact value) {
        this.senderContact = value;
    }

    /**
     * Gets the value of the employerContact property.
     *
     * @return
     *     possible object is
     *     {@link TContact }
     *
     */
    public TContact getEmployerContact() {
        return employerContact;
    }

    /**
     * Sets the value of the employerContact property.
     *
     * @param value
     *     allowed object is
     *     {@link TContact }
     *
     */
    public void setEmployerContact(TContact value) {
        this.employerContact = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return
     *     possible object is
     *     {@link TBody }
     *
     */
    public TBody getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value
     *     allowed object is
     *     {@link TBody }
     *     
     */
    public void setBody(TBody value) {
        this.body = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
