//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 12:34:30 PM CET 
//


package com.sp.ScientificPublications.models.cover_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sender-contact" type="{http://www.ftn.uns.ac.rs/scientific-publication}TContact"/>
 *         &lt;element name="employer-contact" type="{http://www.ftn.uns.ac.rs/scientific-publication}TContact"/>
 *         &lt;element name="body" type="{http://www.ftn.uns.ac.rs/scientific-publication}TBody"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderContact",
    "employerContact",
    "body"
})
@XmlRootElement(name = "cover-letter")
public class CoverLetter {

    @XmlElement(name = "sender-contact", required = true)
    protected TContact senderContact;
    @XmlElement(name = "employer-contact", required = true)
    protected TContact employerContact;
    @XmlElement(required = true)
    protected TBody body;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the senderContact property.
     * 
     * @return
     *     possible object is
     *     {@link TContact }
     *     
     */
    public TContact getSenderContact() {
        return senderContact;
    }

    /**
     * Sets the value of the senderContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContact }
     *     
     */
    public void setSenderContact(TContact value) {
        this.senderContact = value;
    }

    /**
     * Gets the value of the employerContact property.
     * 
     * @return
     *     possible object is
     *     {@link TContact }
     *     
     */
    public TContact getEmployerContact() {
        return employerContact;
    }

    /**
     * Sets the value of the employerContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContact }
     *     
     */
    public void setEmployerContact(TContact value) {
        this.employerContact = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link TBody }
     *     
     */
    public TBody getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBody }
     *     
     */
    public void setBody(TBody value) {
        this.body = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
