//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 12:10:40 AM CET 
//


package com.sp.ScientificPublications.models.cover_letter;

import rs.ac.uns.ftn.common.TParagraphs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBody"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="salutation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paragraphs" type="{http://www.ftn.uns.ac.rs/common}TParagraphs"/&gt;
 *         &lt;element name="closure" type="{http://www.ftn.uns.ac.rs/scientific-publication}TClosure"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBody", propOrder = {
    "salutation",
    "paragraphs",
    "closure"
})
public class TBody {

    @XmlElement(required = true)
    protected String salutation;
    @XmlElement(required = true)
    protected TParagraphs paragraphs;
    @XmlElement(required = true)
    protected TClosure closure;

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the paragraphs property.
     * 
     * @return
     *     possible object is
     *     {@link TParagraphs }
     *     
     */
    public TParagraphs getParagraphs() {
        return paragraphs;
    }

    /**
     * Sets the value of the paragraphs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TParagraphs }
     *     
     */
    public void setParagraphs(TParagraphs value) {
        this.paragraphs = value;
    }

    /**
     * Gets the value of the closure property.
     * 
     * @return
     *     possible object is
     *     {@link TClosure }
     *     
     */
    public TClosure getClosure() {
        return closure;
    }

    /**
     * Sets the value of the closure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClosure }
     *     
     */
    public void setClosure(TClosure value) {
        this.closure = value;
    }

}
