//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 12:34:30 PM CET 
//


package com.sp.ScientificPublications.models.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TParagraphBold_QNAME = new QName("http://www.ftn.uns.ac.rs/common", "bold");
    private final static QName _TParagraphItalic_QNAME = new QName("http://www.ftn.uns.ac.rs/common", "italic");
    private final static QName _TParagraphUnderline_QNAME = new QName("http://www.ftn.uns.ac.rs/common", "underline");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Institution }
     * 
     */
    public Institution createInstitution() {
        return new Institution();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link TParagraph }
     * 
     */
    public TParagraph createTParagraph() {
        return new TParagraph();
    }

    /**
     * Create an instance of {@link TAuthors }
     * 
     */
    public TAuthors createTAuthors() {
        return new TAuthors();
    }

    /**
     * Create an instance of {@link TSection }
     * 
     */
    public TSection createTSection() {
        return new TSection();
    }

    /**
     * Create an instance of {@link TParagraphs }
     * 
     */
    public TParagraphs createTParagraphs() {
        return new TParagraphs();
    }

    /**
     * Create an instance of {@link TSections }
     * 
     */
    public TSections createTSections() {
        return new TSections();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/common", name = "bold", scope = TParagraph.class)
    public JAXBElement<String> createTParagraphBold(String value) {
        return new JAXBElement<String>(_TParagraphBold_QNAME, String.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/common", name = "italic", scope = TParagraph.class)
    public JAXBElement<String> createTParagraphItalic(String value) {
        return new JAXBElement<String>(_TParagraphItalic_QNAME, String.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/common", name = "underline", scope = TParagraph.class)
    public JAXBElement<String> createTParagraphUnderline(String value) {
        return new JAXBElement<String>(_TParagraphUnderline_QNAME, String.class, TParagraph.class, value);
    }

}
